version: '3'

volumes:
  tg_bot_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - tg_bot_data:/var/lib/postgresql/data
  django_admin:
    build: ./django_admin/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/tg_bot_app/collected_static/
  bot_project:
    build:
      context: .
      dockerfile: ./bot_project/Dockerfile
    env_file: .env
  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
