# Generated by Django 5.0.2 on 2024-02-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID пользователя в телеграмм'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Ник пользователя'),
        ),
    ]
