# Generated by Django 5.0.2 on 2024-02-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_clients_user_id_alter_clients_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название рассылки')),
                ('text', models.TextField(verbose_name='текст рассылки')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата отправки')),
                ('recipients', models.ManyToManyField(related_name='recipients', to='admin_panel.clients', verbose_name='получатели')),
            ],
            options={
                'verbose_name': 'Отправленная Рассылка',
                'verbose_name_plural': 'Отправленные Рассылки',
                'ordering': ['-id'],
            },
        ),
    ]
